### ISSUE TITLE
Updates to readme

### ISSUE THREAD

**Issue by nato2k** [ppamidimarri/drybox#1]
First of all, excellent stuff, I am using it sans the Arduino/LEDs.

Just some things I experienced while installing.

need to also apt install smbus
need to `sudo mysql -u root -p` rather than just `mysql -u root -p`
need to `use drybox;` before creating the table

Also might want to mention that mysql needs to be exited and re-logged into as sensor, I knew what it needed from experience but others might not.

Thanks for creating!

**Comment by ppamidimarri** [comment]
Thanks, I have updated the readme with all these corrections.
